version: '3'

services:
  dio-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev:/dev
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
    network_mode: host
    privileged: true